var FontNames = {
	'AMOSB___': 'アモス　ボールド',
	'AMOSBI__': 'アモス　ボールドイタリック',
	'AMOSEB__': 'アモス　EXボールド',
	'AMOSEBI_': 'アモス　EXボールドイタリック',
	'AMOSEI__': 'アモス　EXイタリック',
	'AMOSEN__': 'アモス　EX',
	'AMOSI___': 'アモス　イタリック',
	'AMOSN___': 'アモス',
	'AMOSTB__': 'アモス　THINボールド',
	'AMOSTBI_': 'アモス　THINボールドイタリック',
	'AMOSTI__': 'アモス　THINイタリック',
	'AMOSTN__': 'アモス　THIN',
	'C018016D': 'クーパー',
	'CAVEMAN_': 'ケイヴマン',
	'DEFECAFO': 'ディフェカ',
	'FATASSFI': 'ファット',
	'GRAFFITI': 'グラフィティー',
	'jaggyfries.ttf': 'ジャギー',
	'americantypewriterstd-bold': 'アメリカン',
	'americantypewriterstd-med': 'ミディアム',
	'Plain Germanica': 'ジャーマニカ',
	'amsterdam': 'アムステルダム',
	'Daft Font': 'ダフト',
	'Megadeth': 'メガデス',
	'MISFITS_': 'ミスフィッツ',
	'NITEMARE': 'ナイトメアー',
	'RUFA': 'ルーファ',
	'renaissance': 'ルネッサンス',
	'WREXHAM_': 'レクハム',
	'AMAZB___': 'アメイズ　ボールド',
	'AMAZDI__': 'アメイズD　イタリック',
	'AMAZDZ__': 'アメイズD　ボールドイタリック',
	'AMAZI___': 'アメイズ　イタリック',
	'AMAZR___': 'アメイズ',
	'AMAZZ___': 'アメイズ　ボールドイタリック',
	'AppleGaramond': 'アップル',
	'AppleGaramond-Bold': 'アップル　ボールド',
	'AppleGaramond-BoldItalic': 'アップル　ボールドイタリック',
	'AppleGaramond-Light': 'アップル　ライト',
	'AppleGaramond-LightItalic': 'アップル　ライトイタリック',
	'MarketingScript': 'マーケティング',
	'MarketingScript-Shadow': 'マーケティング　シャドウ',
	'Anderson': 'アンダーソン',
	'CloisterBlack': 'クリスター',
	'Army Condensed': 'アーミーCondense',
	'Army Expanded': 'アーミーEx',
	'Army Thin': 'アーミーThin',
	'Army Wide': 'アーミーWide',
	'Army': 'アーミー',
	'ENGLB___': 'イングランド　ボールド',
	'ENGLBI__': 'イングランド　ボールドイタリック',
	'ENGLI___': 'イングランド　イタリック',
	'ENGLN___': 'イングランド',
	'judasc__': 'アイロン',
	'All Star Resort': 'オールスター',
	'COLLEGEB': 'カレッジ',
	'DEFTONE': 'デフトーン',
	'varsity_regular': 'バーシティ',
	'ARCADEPI': 'アーケデピックス',
	'NIRVANA': 'ニルバーナ',
	'vintage': 'ヴィンテージ',
	'Yahoo': 'ヤフー',
	'GREMSB__': 'グレムリン　ボールド',
	'GREMSBI_': 'グレムリン　ボールドイタリック',
	'GREMSI__': 'グレムリン　イタリック',
	'GREMSN__': 'グレムリン',
	'LCD2B___': 'LCD　ボールド',
	'LCD2L___': 'LCD　ライト',
	'LCD2N___': 'LCD',
	'LCD2U___': 'LCD　ウルトラ',
	'DFGOTC': '極太ゴシック',
	'DFKAI9': '極太楷書',
	'DFMINC': '極太明朝',
	'CRBajoka-R': 'バジョカ',
	'DCKGMC': '籠',
	'DCYSM7': '寄席',
	'DFSGYO5': '祥南行書',
	'KswGoryuNew': '豪龍',
	'samurai': 'さむらい',
	'SMODERN': '昭和モダン',
	'DFCRS9': 'クラフト墨',
	'DFMRGC': '極太丸ゴシック',
	'DFMRM9': 'まるもじ',
	'nipple': 'ニップル',
	'DFRULE7': '流麗',
	'DFSHT7': 'しんてん',
	'DFSOGE7': 'そうげい'
}
